#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTANG2,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTANG,          sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     rotation,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     lift,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    midarm,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    handtilt,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-angle.h"

int base_rotation = HTANGreadAccumulatedAngle(HTANG2), base_lift = HTANGreadAccumulatedAngle(HTANG), mid_angle = ServoValue[midarm];
int s = 20; //speed
float length = 29.5; //arm segment length

void level(){
	servo[handtilt]=ServoValue[midarm]-base_lift/180.0*255.0;
}

void set_arm(float yaw, float pitch, float mid){
	int initial_pitch = HTANGreadAccumulatedAngle(HTANG);//new
	int yaw_speed = 20;
	int pitch_speed = 20;
	if (base_rotation > yaw)
		yaw_speed = -yaw_speed;
	if (base_lift > pitch)
		pitch_speed = -pitch_speed;
	while((yaw_speed!=0)||(pitch_speed!=0)){
		base_rotation = HTANGreadAccumulatedAngle(HTANG2);
		base_lift = HTANGreadAccumulatedAngle(HTANG);
		//servo[midarm]=mid;
		servo[midarm]=mid_angle+(mid-mid_angle)*((base_lift-initial_pitch)/(pitch-initial_pitch));
		if ((yaw_speed < 0) && (yaw >= base_rotation))
			yaw_speed = 0;
		if ((yaw_speed > 0) && (yaw <= base_rotation))
			yaw_speed = 0;
		if ((pitch_speed < 0) && (pitch >= base_lift))
			pitch_speed = 0;
		if ((pitch_speed > 0) && (pitch <= base_lift))
			pitch_speed = 0;
		motor[lift]=pitch_speed;
		motor[rotation]=yaw_speed;
		level();//new, not totally necessary
	}
	servo[midarm]=mid;//new
	mid_angle=mid;//new
	motor[lift]=0;
	motor[rotation]=0;
}

void reset(){
	set_arm(0,0,0);
}

void gotopoint(float x, float y, float z){
	float h  = sqrt(x*x + y*y + z*z)/2;//(sqrt(sqrt(x*x + y*y)*sqrt(x*x + y*y) + z*z))/2;
	float a1 = acos(h/length)/PI*180;
	float a2 = atan(z/sqrt(x*x + y*y))/PI*180;
	float a3 = asin(h/length)/PI*510; //510 = 2 * 255
	float a4 = atan(x/y)/PI*180;
	set_arm(a4, a1 + a2, 255-a3);
}

task main () {
  wait10Msec(100);
  reset();
  gotopoint(20,20,20);
  wait10Msec(30);
  servo[handtilt]=255;
  wait10Msec(30);
  servo[handtilt]=0;
  wait10Msec(30);
  servo[handtilt]=255;
  wait10Msec(30);
  servo[handtilt]=0;
  wait10Msec(30);
  gotopoint(-30,10,-20);
  wait10Msec(50);
  gotopoint(0,40,0);
  wait10Msec(50);
  gotopoint(-40,40,0);
  wait10Msec(50);
  gotopoint(10,10,-5);
  wait10Msec(50);
  /*servo[servo3]=128;
  wait10Msec(100);
  servo[servo3]=150;
  wait10Msec(100);
  servo[servo4]=128;
  wait10Msec(100);
  servo[servo4]=150;
  wait10Msec(500);*/
  reset();
  wait10Msec(300);
}


/*
Angle sensor driver by Xander Soldaat (xander_at_botbench.com)
*/
